# Generated by Django 3.1.3 on 2020-11-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_auto_20201113_1420'),
        ('historicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicos',
            name='id_agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='agendamentos.agendamentos'),
        ),
    ]
