# Generated by Django 3.1.3 on 2020-11-13 14:20

from django.db import migrations, models
import pacientes.models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pacientes.models.imagem_paciente),
        ),
    ]
