# Generated by Django 3.1.3 on 2020-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
