# Generated by Django 3.1.3 on 2020-11-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_pacientes_avatar'),
        ('agendamentos', '0002_auto_20201112_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pacientes.pacientes'),
        ),
    ]
