# Generated by Django 3.1.3 on 2020-11-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.TextField(unique=True)),
                ('disponivel', models.BooleanField()),
            ],
            options={
                'db_table': 'horarios',
                'managed': True,
            },
        ),
    ]
