# Generated by Django 3.1.3 on 2020-11-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='horario',
            field=models.IntegerField(unique=True),
        ),
    ]
